---
language: python
python:
  - "3.6"

# Install python packages for ansible and linters.
# Install a minimal TexLive installation for LaTeX support.
install:
  - "sudo apt-get install chktex xzdec texlive-latex-base -y"
  - "tlmgr init-usertree"
  - "tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final"
  - "tlmgr update longtable minted booktabs graphicx caption array"
  - "pip install -r requirements.txt"

# Execute linting tests before running the main playbook.
# lacheck and chktex apparently always return rc=0 
before_script:
  - "make lint"
  - "make draft"
  - "make clean"

# Make the PDF itself
script:
  - "make pdf"
...
